"""empty message

Revision ID: 5e3ddffbe540
Revises: 3030bd2ee67b
Create Date: 2020-02-16 19:42:58.422317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3ddffbe540'
down_revision = '3030bd2ee67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('show_venue_id_fkey', 'show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
